name: jaguar_example_json
description: Example to demonstrate how to read JSON requests and write JSON responses using Jaguar web framework.
version: 2.1.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/jaguar-examples/json

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  jaguar: ^2.1.8
  jaguar_resty: ^2.5.5
  http: ^0.11.3

dev_dependencies:
  test: ^1.2.0
