name: json
description: Examples to demonstrate how to implement JSON routes using Jaguar web framework
version: 0.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar: ">=0.5.3 <0.6.0"
  jaguar_reflect: '>=0.5.1 <0.6.0'

dev_dependencies:
  test: ^0.12.0
