name: json
description: Examples to demonstrate how to implement JSON routes using Jaguar web framework
version: 0.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  jaguar: ^2.1.8
  jaguar_resty: ^2.5.5

dev_dependencies:
  test: ^1.0.0
